### ISSUE TITLE
Launcher 2.0?

### ISSUE THREAD

**Issue by damccull** [LovingMelody/nix-citizen#22]
I used your fancy nix installer thing with my flake to install Star Citizen, but I noticed it uses the legacy installer. Is there and option to use the new one?

**Comment by LovingMelody** [comment]
I use wine-ge which is not supported, the development branch can install it which uses umu but the branch is updated very slowly and may suddenly break.
2.0 launcher will not be considered as an option until:
- 1.X.X launcher is not supported (which it will be for quite  some time)
- the resource consumption is greatly reduced 
- wine-ge gets updated (not likely considering it hasn't for many months now)

**Comment by damccull** [comment]
Fair enough. Why this particular version of wine? It has the required patches already? Sorry, I'm a complete wine newbie. Steam usually handles it for me with proton.

**Comment by LovingMelody** [comment]
Yea, wine 9.5 or newer is needed, I use wine-ge since I still  get good performance results out of it, I may consider looking into just using native wine and see how that runs since, wine-ge hasn't received an update in a while.

**Comment by LovingMelody** [comment]
Pinning issue for feedback, if theres an update on performance, this issue will also be revisited.

**Comment by damccull** [comment]
Thanks for the info! I'll go do some learning about wine.

**Comment by LovingMelody** [comment]
A newer wine version is being added through umu, launcher's performance issues are still present & umu is not the default until a stable release of umu.

**Comment by damccull** [comment]
Can I ask what "umu" is? This is, again, new to me.

**Comment by LovingMelody** [comment]
Further updates on this: I'm aware of the push for the 2.0 launcher this year.
Part of what is needed is already added for ProtonGE-9-12 (Used in umu). Just need to package winetricks-git

**Comment by LovingMelody** [comment]
> Can I ask what "umu" is? This is, again, new to me.

https://github.com/Open-Wine-Components/umu-launcher

Basically a way of using proton outside of steam

**Comment by LovingMelody** [comment]
Launcher 2.0 is now implemented.

**Comment by damccull** [comment]
Oh, fun. Thanks. I'll get that swapped over :D

**Comment by damccull** [comment]
How do I swap to the new launcher? Lol. I just updated, though maybe I didn't get _this_ update yet.

**Comment by LovingMelody** [comment]
You can either reinstall or use the prompt to update to the 2.0 launcher in the official launcher. 
If you reinstall backup your LIVE folder so you can copy it back and not have to download the whole game again.

**Comment by damccull** [comment]
Thanks!

**Comment by damccull** [comment]
Well, it's been a few weeks, but I have just come around to trying this out. I'm not getting a launcher update prompt in the 1.0 launcher, and I've tried to uninstall and reinstall, but I must be doing it wrong in nix. I removed it from my flake and ran nixos-rebuild, then I moved the entire wine installation folder into a backup location, re-enabled it in my flake and rebuilt again, but I have the 1.0 launcher still. Do I just need to somehow wine-run the installer for 2.0 manually?

**Comment by LovingMelody** [comment]
You may need to if it isn't working, if you have been overriding the nix-gaming flake input for nix-citizen the package definition for 2.X just got merged not too long ago. If you do, the standard "star-citizen" package uses wineWowPackages.stable.

**Comment by damccull** [comment]
Thank you! I'll try it out.

**Comment by damccull** [comment]
Ok, well I am getting dll errors running it that way.

```
00cc:err:module:import_dll Library coml2.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") not found
00cc:err:module:import_dll Library ole32.dll (which is needed by L"Z:\\home\\david\\Games\\RSI Launcher-Setup-2.0.5.exe") not found
00cc:err:module:loader_init Importing dlls for L"Z:\\home\\david\\Games\\RSI Launcher-Setup-2.0.5.exe" failed, status c0000135
```

I also tried moving (backing up) the star citizen folder and trying to launch it again from the applications menu. That rebuilt wine, but I get a javascript error on startup.
![image](https://github.com/user-attachments/assets/399698e7-fb7d-40cd-8d18-dcecf87d04c0)


My flake includes this, and I just enable=true your SC option:

```nix
    nix-gaming = {
      url = "github:fufexan/nix-gaming";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nix-citizen = {
      url = "github:LovingMelody/nix-citizen";
      inputs.nix-gaming.follows = "nix-gaming";
    };
```
